from app.models import db, Size

def seed_sizes():

    xsmall = Size(sizeDescription='xsmall')
    small = Size(sizeDescription='small')
    medium = Size(sizeDescription='medium')
    large = Size(sizeDescription='large')
    xlarge = Size(sizeDescription='xlarge')
    xxlarge = Size(sizeDescription='xxlarge')
    xxxlarge = Size(sizeDescription='xxxlarge')
    doublezero = Size(sizeDescription='00')
    zero = Size(sizeDescription='0')
    one = Size(sizeDescription='1')
    two = Size(sizeDescription='2')
    three = Size(sizeDescription='3')
    four = Size(sizeDescription='4')
    five = Size(sizeDescription='5')
    six = Size(sizeDescription='6')
    seven = Size(sizeDescription='7')
    eight = Size(sizeDescription='8')
    nine = Size(sizeDescription='9')
    ten = Size(sizeDescription='10')
    eleven = Size(sizeDescription='11')
    twelve = Size(sizeDescription='12')
    thirteen = Size(sizeDescription='13')
    fourteen = Size(sizeDescription='14')
    fifteen = Size(sizeDescription='15')
    sixteen = Size(sizeDescription='16')
    seventeen = Size(sizeDescription='17')
    eighteen = Size(sizeDescription='18')
    nineteen = Size(sizeDescription='19')
    twenty = Size(sizeDescription='20')
    onesize = Size(sizeDescription='one size')

    db.session.add(xsmall)
    db.session.add(small)
    db.session.add(medium)
    db.session.add(large)
    db.session.add(xlarge)
    db.session.add(xxlarge)
    db.session.add(xxxlarge)
    db.session.add(zero)
    db.session.add(one)
    db.session.add(two)
    db.session.add(three)
    db.session.add(four)
    db.session.add(five)
    db.session.add(six)
    db.session.add(seven)
    db.session.add(eight)
    db.session.add(nine)
    db.session.add(ten)
    db.session.add(eleven)
    db.session.add(twelve)
    db.session.add(thirteen)
    db.session.add(fourteen)
    db.session.add(fifteen)
    db.session.add(sixteen)
    db.session.add(seventeen)
    db.session.add(eighteen)
    db.session.add(nineteen)
    db.session.add(twenty)
    db.session.add(onesize)

    db.session.commit()

def undo_sizes():
    db.session.execute('TRUNCATE sizes;')
    db.session.commit()
