from app.models import db, SubCategory

def seed_subCategories():

    Blouses = SubCategory(subCategoryName='Blouses', categoryId=1)
    Tanks = SubCategory(subCategoryName='Tanks', categoryId=1)
    DressShirts = SubCategory(subCategoryName='Dress Shirts', categoryId=1)
    SweatShirts = SubCategory(subCategoryName='Sweat Shirts', categoryId=1)
    LongSleeve = SubCategory(subCategoryName='Long Sleeve', categoryId=1)
    ShortSleeve = SubCategory(subCategoryName='Short Sleeve', categoryId=1)
    CroppedTops = SubCategory(subCategoryName='CroppedTops', categoryId=1)
    Pants = SubCategory(subCategoryName='Pants', categoryId=2)
    Shorts = SubCategory(subCategoryName='Shorts', categoryId=2)
    Skirts = SubCategory(subCategoryName='Skirts', categoryId=2)
    Coats = SubCategory(subCategoryName='Coats', categoryId=3)
    Blazers = SubCategory(subCategoryName='Blazers', categoryId=3)
    Suits = SubCategory(subCategoryName='Suit Jackets', categoryId=3)
    Raincoats = SubCategory(subCategoryName='Rain Coats', categoryId=3)
    Windbreakers = SubCategory(subCategoryName='Windbreakers', categoryId=3)
    Bombers = SubCategory(subCategoryName='Bombers', categoryId=3)
    Vests = SubCategory(subCategoryName='Vests', categoryId=3)
    Cardigans = SubCategory(subCategoryName='Cardigan', categoryId=4)
    SweaterVests = SubCategory(subCategoryName='Sweater Vests', categoryId=4)
    Pullovers = SubCategory(subCategoryName='Pullovers', categoryId=4)
    TurtleNecks = SubCategory(subCategoryName='Turtlenecks', categoryId=4)
    Sneakers = SubCategory(subCategoryName='Sneakers', categoryId=6)
    Heels = SubCategory(subCategoryName='Heels', categoryId=6)
    Boots = SubCategory(subCategoryName='Boots', categoryId=6)
    Sandals = SubCategory(subCategoryName='Sandals', categoryId=6)
    Slippers = SubCategory(subCategoryName='Slippers', categoryId=6)
    Flats = SubCategory(subCategoryName='Flats', categoryId=6)
    Loafers = SubCategory(subCategoryName='Loafers', categoryId=6)
    AnkleBoots = SubCategory(subCategoryName='Ankle Boots', categoryId=6)
    Business = SubCategory(subCategoryName='Business', categoryId=6)
    Sports = SubCategory(subCategoryName='Sports', categoryId=6)
    Hobo = SubCategory(subCategoryName='Hobo', categoryId=7)
    Baguette = SubCategory(subCategoryName='Baguette', categoryId=7)
    Duffle = SubCategory(subCategoryName='Duffle', categoryId=7)
    Shopper = SubCategory(subCategoryName='Shopper', categoryId=7)
    Wristlet = SubCategory(subCategoryName='Wristlet', categoryId=7)
    Messenger = SubCategory(subCategoryName='Messenger', categoryId=7)
    Clutch = SubCategory(subCategoryName='Clutch', categoryId=7)
    Satchel = SubCategory(subCategoryName='Satchel', categoryId=7)
    Tote = SubCategory(subCategoryName='Tote', categoryId=7)
    Bucket = SubCategory(subCategoryName='Bucket', categoryId=7)
    Backpack = SubCategory(subCategoryName='Backpack', categoryId=7)
    Bracelets = SubCategory(subCategoryName='Bracelets', categoryId=5)
    Necklaces = SubCategory(subCategoryName='Necklaces', categoryId=5)
    Watches = SubCategory(subCategoryName='Watches', categoryId=5)
    Scarves = SubCategory(subCategoryName='Scarves', categoryId=5)
    Gloves = SubCategory(subCategoryName='Gloves', categoryId=5)
    Wraps = SubCategory(subCategoryName='Wraps', categoryId=5)
    Sunglasses = SubCategory(subCategoryName='Sunglasses', categoryId=5)
    Hair = SubCategory(subCategoryName='Hats', categoryId=5)
    Rings = SubCategory(subCategoryName='Rings', categoryId=5)
    Tights = SubCategory(subCategoryName='Tights', categoryId=5)
    Ties = SubCategory(subCategoryName='Ties', categoryId=5)
    Earrings = SubCategory(subCategoryName='Earrings', categoryId=5)
    Sets = SubCategory(subCategoryName='Sets', categoryId=8)
    Loungewear = SubCategory(subCategoryName='Loungewear', categoryId=8)
    NightGown = SubCategory(subCategoryName='NightGown', categoryId=8)
    Negligee = SubCategory(subCategoryName='Negligee', categoryId=8)
    Robe = SubCategory(subCategoryName='Robe', categoryId=8)
    NightShirts = SubCategory(subCategoryName='Night Shirts', categoryId=8)
    ShortDresses = SubCategory(subCategoryName='Short Dresses', categoryId=9)
    MaxiDress = SubCategory(subCategoryName='Maxi Dress', categoryId=9)
    Party = SubCategory(subCategoryName='Party', categoryId=9)
    SunDresses = SubCategory(subCategoryName='Sun Dresses', categoryId=9)
    WorkDresses = SubCategory(subCategoryName='Work Dresses', categoryId=9)
    Formal = SubCategory(subCategoryName='Formal', categoryId=9)
    Cocktail = SubCategory(subCategoryName='Cocktail', categoryId=9)
    ShirtDresses = SubCategory(subCategoryName='Shirt Dresses', categoryId=9)
    LongRomps = SubCategory(subCategoryName='Long Rompers', categoryId=10)
    ShortRomps = SubCategory(subCategoryName='Short Rompers', categoryId=10)
    DressyRomps = SubCategory(subCategoryName='Dressy Rompers', categoryId=10)
    OnePieces = SubCategory(subCategoryName='One Pieces', categoryId=11)
    Bikinis = SubCategory(subCategoryName='Bikini', categoryId=11)
    Tankinis = SubCategory(subCategoryName='Tankini', categoryId=11)
    Burkinis = SubCategory(subCategoryName='NightShirts', categoryId=11)

    db.session.add(Blouses)
    db.session.add(Tanks)
    db.session.add(DressShirts)
    db.session.add(SweatShirts)
    db.session.add(LongSleeve)
    db.session.add(ShortSleeve)
    db.session.add(CroppedTops)
    db.session.add(Pants)
    db.session.add(Shorts)
    db.session.add(Skirts)
    db.session.add(Blazers)
    db.session.add(Coats)
    db.session.add(Suits)
    db.session.add(Raincoats)
    db.session.add(Windbreakers)
    db.session.add(Vests)
    db.session.add(Cardigans)
    db.session.add(Bombers)
    db.session.add(SweaterVests)
    db.session.add(Pullovers)
    db.session.add(TurtleNecks)
    db.session.add(Sneakers)
    db.session.add(Boots)
    db.session.add(Sandals)
    db.session.add(Slippers)
    db.session.add(Flats)
    db.session.add(Loafers)
    db.session.add(AnkleBoots)
    db.session.add(Business)
    db.session.add(Sports)
    db.session.add(Hobo)
    db.session.add(Baguette)
    db.session.add(Duffle)
    db.session.add(Wristlet)
    db.session.add(Shopper)
    db.session.add(Messenger)
    db.session.add(Clutch)
    db.session.add(Satchel)
    db.session.add(Tote)
    db.session.add(Bucket)
    db.session.add(Backpack)
    db.session.add(Bracelets)
    db.session.add(Necklaces)
    db.session.add(Wraps)
    db.session.add(Watches)
    db.session.add(Scarves)
    db.session.add(Gloves)
    db.session.add(Sunglasses)
    db.session.add(Hair)
    db.session.add(Rings)
    db.session.add(Tights)
    db.session.add(Ties)
    db.session.add(Earrings)
    db.session.add(Sets)
    db.session.add(Loungewear)
    db.session.add(NightGown)
    db.session.add(Negligee)
    db.session.add(Robe)
    db.session.add(NightShirts)
    db.session.add(ShortDresses)
    db.session.add(MaxiDress)
    db.session.add(Party)
    db.session.add(SunDresses)
    db.session.add(WorkDresses)
    db.session.add(Formal)
    db.session.add(Cocktail)
    db.session.add(ShirtDresses)
    db.session.add(LongRomps)
    db.session.add(ShortRomps)
    db.session.add(DressyRomps)
    db.session.add(OnePieces)
    db.session.add(Bikinis)
    db.session.add(Tankinis)
    db.session.add(Burkinis)

    db.session.commit()

def undo_subCategories():
    db.session.execute('TRUNCATE subCategories;')
    db.session.commit()
