"""empty message

Revision ID: 254dbba00318
Revises: dda25b7f9035
Create Date: 2021-02-03 14:04:38.492990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254dbba00318'
down_revision = 'dda25b7f9035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('leader_id', 'follower_id')
    )
    op.create_table('itemWeather',
    sa.Column('weatherId', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['itemId'], ['items.id'], ),
    sa.ForeignKeyConstraint(['weatherId'], ['weather.id'], )
    )
    op.drop_table('follows')
    op.drop_table('Weathering')
    op.alter_column('itemColors', 'colorId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('itemColors', 'itemId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('itemStyles', 'itemId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('itemStyles', 'styledId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('items', sa.Column('subCatergoyId', sa.Integer(), nullable=False))
    op.alter_column('items', 'borrowedId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items', 'sizeId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'items', 'subcategories', ['subCatergoyId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.alter_column('items', 'sizeId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('items', 'borrowedId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('items', 'subCatergoyId')
    op.alter_column('itemStyles', 'styledId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('itemStyles', 'itemId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('itemColors', 'itemId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('itemColors', 'colorId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('Weathering',
    sa.Column('weatherId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('itemId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['itemId'], ['items.id'], name='Weathering_itemId_fkey'),
    sa.ForeignKeyConstraint(['weatherId'], ['weather.id'], name='Weathering_weatherId_fkey')
    )
    op.create_table('follows',
    sa.Column('userFollowed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userFollowing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userFollowed'], ['users.id'], name='follows_userFollowed_fkey'),
    sa.ForeignKeyConstraint(['userFollowing'], ['users.id'], name='follows_userFollowing_fkey')
    )
    op.drop_table('itemWeather')
    op.drop_table('followers')
    # ### end Alembic commands ###
