"""empty message

Revision ID: ca1e6fc8bb41
Revises: 
Create Date: 2021-02-10 03:55:17.334658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1e6fc8bb41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sizeDescription', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('styleType', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('undies', sa.Integer(), nullable=True),
    sa.Column('bras', sa.Integer(), nullable=True),
    sa.Column('socks', sa.Integer(), nullable=True),
    sa.Column('tees', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weatherType', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('borrow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrowerId', sa.Integer(), nullable=False),
    sa.Column('dateBorrowed', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=2500), nullable=True),
    sa.ForeignKeyConstraint(['borrowerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followers',
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('leader_id', 'follower_id')
    )
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subCategoryName', sa.String(length=50), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subCategoryId', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('sizeId', sa.Integer(), nullable=True),
    sa.Column('purchasedAt', sa.String(length=255), nullable=True),
    sa.Column('clean', sa.Boolean(), nullable=True),
    sa.Column('datePurchased', sa.Date(), nullable=True),
    sa.Column('lastWorn', sa.Date(), nullable=True),
    sa.Column('timesWorn', sa.Integer(), nullable=True),
    sa.Column('borrowedId', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrowedId'], ['borrow.id'], ),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sizeId'], ['sizes.id'], ),
    sa.ForeignKeyConstraint(['subCategoryId'], ['subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemColors',
    sa.Column('colorId', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colorId'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['itemId'], ['items.id'], )
    )
    op.create_table('itemStyles',
    sa.Column('styledId', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['itemId'], ['items.id'], ),
    sa.ForeignKeyConstraint(['styledId'], ['styles.id'], )
    )
    op.create_table('itemWeather',
    sa.Column('weatherId', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['itemId'], ['items.id'], ),
    sa.ForeignKeyConstraint(['weatherId'], ['weather.id'], )
    )
    op.create_table('outfits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.Column('event', sa.Text(), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=2500), nullable=True),
    sa.Column('jacketId', sa.Integer(), nullable=True),
    sa.Column('bagId', sa.Integer(), nullable=True),
    sa.Column('shoeId', sa.Integer(), nullable=True),
    sa.Column('topId', sa.Integer(), nullable=True),
    sa.Column('bottomId', sa.Integer(), nullable=True),
    sa.Column('dressId', sa.Integer(), nullable=True),
    sa.Column('accessoryOne', sa.Integer(), nullable=True),
    sa.Column('accessoryTwo', sa.Integer(), nullable=True),
    sa.Column('accessoryThree', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accessoryOne'], ['items.id'], ),
    sa.ForeignKeyConstraint(['accessoryThree'], ['items.id'], ),
    sa.ForeignKeyConstraint(['accessoryTwo'], ['items.id'], ),
    sa.ForeignKeyConstraint(['bagId'], ['items.id'], ),
    sa.ForeignKeyConstraint(['bottomId'], ['items.id'], ),
    sa.ForeignKeyConstraint(['creatorId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dressId'], ['items.id'], ),
    sa.ForeignKeyConstraint(['jacketId'], ['items.id'], ),
    sa.ForeignKeyConstraint(['shoeId'], ['items.id'], ),
    sa.ForeignKeyConstraint(['topId'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outfits')
    op.drop_table('itemWeather')
    op.drop_table('itemStyles')
    op.drop_table('itemColors')
    op.drop_table('items')
    op.drop_table('subcategories')
    op.drop_table('followers')
    op.drop_table('borrow')
    op.drop_table('weather')
    op.drop_table('users')
    op.drop_table('styles')
    op.drop_table('sizes')
    op.drop_table('colors')
    op.drop_table('categories')
    # ### end Alembic commands ###
